CREATE TYPE "OrderSource" AS ENUM ('CLIENT_APP', 'WORKER_PHONE');

ALTER TABLE "Order"
ADD COLUMN "source" "OrderSource" NOT NULL DEFAULT 'CLIENT_APP';

ALTER TABLE "User"
ADD COLUMN "isProvisional" BOOLEAN NOT NULL DEFAULT false;
