import {
  Baby,
  Bike,
  BookOpen,
  Brush,
  Camera,
  Car,
  ChefHat,
  Droplets,
  Flame,
  GraduationCap,
  Grid2X2,
  Hammer,
  HardHat,
  HeartHandshake,
  Laptop,
  Lock,
  Paintbrush,
  PaintRoller,
  Printer,
  Scissors,
  Shovel,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  TreePine,
  Truck,
  Wifi,
  Wrench,
  Zap
} from "lucide-react-native";

export const CATEGORY_ICONS = Object.freeze({
  "wrench": Wrench,
  "zap": Zap,
  "flame": Flame,
  "hammer": Hammer,
  "snowflake": Snowflake,
  "paint": PaintRoller,
  "sparkles": Sparkles,
  "brush": Brush,
  "hard-hat": HardHat,
  "paintbrush": Paintbrush,
  "sofa": Sofa,
  "car": Car,
  "truck": Truck,
  "bike": Bike,
  "smartphone": Smartphone,
  "laptop": Laptop,
  "printer": Printer,
  "camera": Camera,
  "wifi": Wifi,
  "lock": Lock,
  "tree": TreePine,
  "shovel": Shovel,
  "droplets": Droplets,
  "scissors": Scissors,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "chef-hat": ChefHat,
  "baby": Baby,
  "heart-handshake": HeartHandshake,
  "grid": Grid2X2
});

export function resolveCategoryIcon(iconKey) {
  return CATEGORY_ICONS[iconKey] || Grid2X2;
}

const iconColors = Object.freeze({
  "wrench": "#0F80B7",
  "zap": "#2CD8A5",
  "flame": "#F97316",
  "hammer": "#2D3748",
  "snowflake": "#60A5FA",
  "paint": "#A855F7",
  "sparkles": "#20BFA5",
  "brush": "#20BFA5",
  "hard-hat": "#D97706",
  "paintbrush": "#A855F7",
  "sofa": "#8B5CF6",
  "car": "#2563EB",
  "truck": "#0F766E",
  "bike": "#0891B2",
  "smartphone": "#4F46E5",
  "laptop": "#475569",
  "printer": "#64748B",
  "camera": "#DB2777",
  "wifi": "#0EA5E9",
  "lock": "#334155",
  "tree": "#16A34A",
  "shovel": "#92400E",
  "droplets": "#0284C7",
  "scissors": "#EC4899",
  "graduation-cap": "#7C3AED",
  "book-open": "#4F46E5",
  "chef-hat": "#EA580C",
  "baby": "#F472B6",
  "heart-handshake": "#E11D48",
  "grid": "#9CA3AF"
});

export function resolveCategoryIconColor(iconKey) {
  return iconColors[iconKey] || iconColors.grid;
}
