const labels: Record<string, string> = {
  ACTIVE: "Faol",
  active: "Faol",
  INACTIVE: "Nofaol",
  inactive: "Nofaol",
  DISABLED: "O'chirilgan",
  waiting: "Kutilmoqda",
  WAITING_RESPONSE: "Javob kutilmoqda",
  busy: "Band",
  BUSY: "Band",
  offline: "Oflayn",
  OFFLINE: "Oflayn",
  available: "Bo'sh",
  AVAILABLE: "Bo'sh",
  draft: "Yangi",
  DRAFT: "Yangi",
  approved: "Tasdiqlangan",
  APPROVED: "Tasdiqlangan",
  suspended: "To'xtatilgan",
  SUSPENDED: "To'xtatilgan",
  completed: "Bajarilgan",
  COMPLETED: "Bajarilgan",
  cancelled: "Bekor qilingan",
  CANCELLED: "Bekor qilingan",
  CREATED: "Yaratilgan",
  ACCEPTED: "Qabul qilingan",
  ON_THE_WAY: "Yo'lda",
  IN_PROGRESS: "Jarayonda",
  PENDING: "Kutilmoqda",
  REVIEWING: "Ko'rib chiqilmoqda",
  RESOLVED: "Hal qilingan",
  DISMISSED: "Rad etilgan",
  ACTION_TAKEN: "Chora ko'rilgan",
  OPEN: "Ochiq",
  CLOSED: "Yopilgan",
  client: "Mijoz",
  CLIENT: "Mijoz",
  provider: "Usta",
  PROVIDER: "Usta",
  admin: "Admin",
  ADMIN: "Admin",
  super_admin: "Bosh admin",
  SUPER_ADMIN: "Bosh admin",
  published: "Ko'rinadi",
  PUBLISHED: "Ko'rinadi",
  hidden: "Yashirilgan",
  HIDDEN: "Yashirilgan",
  NONE: "Yo'naltirishsiz",
  CATEGORY: "Kategoriya",
  URL: "Havola",
  USER: "Foydalanuvchi",
  WORKER: "Usta",
  MESSAGE: "Xabar",
  REVIEW: "Sharh",
  ORDER: "Buyurtma",
  SUPPORT_TICKET: "Yordam murojaati",
  SPAM: "Spam",
  ABUSE: "Suiiste'mol",
  HARASSMENT: "Tazyiq",
  FRAUD: "Firibgarlik",
  INAPPROPRIATE_CONTENT: "Nomaqbul kontent",
  SAFETY_RISK: "Xavfsizlik xatari",
  OTHER: "Boshqa",
  ENV_ADMIN: "Muhit admini",
  ADMIN_ACCOUNT: "Admin hisobi",
  CLIENT_APP: "Mijoz ilovasi",
  WORKER_APP: "Usta ilovasi",
  FAST: "Tez",
  SCHEDULED: "Rejalashtirilgan",
  tashkent: "Toshkent"
};

const auditActions: Record<string, string> = {
  "admin.created": "Admin yaratildi",
  "admin.updated": "Admin yangilandi",
  "admin.enabled": "Admin faollashtirildi",
  "admin.disabled": "Admin o'chirildi",
  "admin.password_reset": "Admin paroli tiklandi",
  "admin.password_changed": "Admin paroli o'zgartirildi",
  "admin.permissions_updated": "Admin ruxsatlari yangilandi",
  "worker.approved": "Usta tasdiqlandi",
  "worker.rejected": "Usta arizasi rad etildi",
  "worker.suspended": "Usta to'xtatildi",
  "worker.unsuspended": "Usta qayta faollashtirildi",
  "worker.deleted": "Usta o'chirildi",
  "user.suspended": "Foydalanuvchi to'xtatildi",
  "report.status_updated": "Shikoyat holati yangilandi",
  "report.resolved": "Shikoyat hal qilindi",
  "report.rejected": "Shikoyat rad etildi"
};

export function adminLabel(value: string | null | undefined) {
  if (!value) return "-";
  return labels[value] || value;
}

export function auditActionLabel(value: string) {
  return auditActions[value] || value;
}
