import {
  Baby,
  Bike,
  BookOpen,
  Brush,
  Camera,
  Car,
  ChefHat,
  Droplets,
  Flame,
  GraduationCap,
  Grid2X2,
  Hammer,
  HardHat,
  HeartHandshake,
  Laptop,
  Lock,
  Paintbrush,
  PaintRoller,
  Printer,
  Scissors,
  Shovel,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  TreePine,
  Truck,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  "wrench": Wrench,
  "zap": Zap,
  "flame": Flame,
  "hammer": Hammer,
  "snowflake": Snowflake,
  "paint": PaintRoller,
  "sparkles": Sparkles,
  "brush": Brush,
  "hard-hat": HardHat,
  "paintbrush": Paintbrush,
  "sofa": Sofa,
  "car": Car,
  "truck": Truck,
  "bike": Bike,
  "smartphone": Smartphone,
  "laptop": Laptop,
  "printer": Printer,
  "camera": Camera,
  "wifi": Wifi,
  "lock": Lock,
  "tree": TreePine,
  "shovel": Shovel,
  "droplets": Droplets,
  "scissors": Scissors,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "chef-hat": ChefHat,
  "baby": Baby,
  "heart-handshake": HeartHandshake,
  "grid": Grid2X2
};

export const categoryIconLabels: Record<string, string> = {
  "wrench": "Santexnika / ta'mirlash",
  "zap": "Elektr ishlari",
  "flame": "Payvandlash / issiqlik",
  "hammer": "Usta xizmatlari",
  "snowflake": "Sovutish / konditsioner",
  "paint": "Bo'yash / ta'mirlash",
  "sparkles": "Tozalash",
  "brush": "Pardozlash",
  "hard-hat": "Qurilish",
  "paintbrush": "Bo'yash / bezatish",
  "sofa": "Mebel",
  "car": "Avtomobil",
  "truck": "Yuk / transport",
  "bike": "Velosiped / mototsikl",
  "smartphone": "Telefon / elektronika",
  "laptop": "Kompyuter / IT",
  "printer": "Printer / ofis uskunalari",
  "camera": "Kamera / foto",
  "wifi": "Internet / tarmoq",
  "lock": "Qulf / xavfsizlik",
  "tree": "Bog'dorchilik / landshaft",
  "shovel": "Yer ishlari",
  "droplets": "Suv xizmatlari",
  "scissors": "Go'zallik / sartarosh",
  "graduation-cap": "Ta'lim",
  "book-open": "Kitob / o'qitish",
  "chef-hat": "Oshpazlik / catering",
  "baby": "Bola parvarishi",
  "heart-handshake": "Parvarish / yordam",
  "grid": "Umumiy / boshqa"
};

export function resolveCategoryIcon(iconKey: string): LucideIcon {
  return categoryIcons[iconKey] || Grid2X2;
}

export function resolveCategoryIconLabel(iconKey: string): string {
  return categoryIconLabels[iconKey] || categoryIconLabels.grid;
}
